### ISSUE TITLE
PMOD connector 3D model error

### ISSUE THREAD

**Issue by DanSGiesbrecht** [icebreaker-fpga/icebreaker#23]
Hi @esden 

I was combing through your design (v1.0c) and noticed that J21 has a duplicated 3D model:

![3d-view](https://user-images.githubusercontent.com/7242621/50649012-f2a59080-0f39-11e9-8f6f-7d4870909c4f.png)

**Comment by esden** [comment]
The offset model should not show up. The second 3d model is a model from the older KiCad 3d library. You might have both installed. You might want to delete old 3d models and only have the new ones installed. I left the old models just in case and prefixed them with `dis` so that KiCad can't find it. It is strange that it shows up at all. What KiCad version do you have installed?

![screenshot from 2019-01-03 18-01-32](https://user-images.githubusercontent.com/17334/50650867-fceb7d00-0f81-11e9-8d72-ad2e9add4985.png)

![screenshot from 2019-01-03 18-02-21](https://user-images.githubusercontent.com/17334/50650882-0379f480-0f82-11e9-9093-d2c39bd30059.png)

**Comment by DanSGiesbrecht** [comment]
Thanks for the quick response! I'm glad to hear that it's just on my end. I have KiCad 5.0.1 installed, with the default 3D library.

**Comment by esden** [comment]
Thank you very much for the contribution. This should now be fixed in all the versions of the board. :)

**Comment by madding1602** [comment]
Hi. I'm trying to get the CAD file made for a project. I need the 2 PMOD connectors on the side, plus the RGBLED, FLASH and CRESET (straight male), along woth the 2 5V connectors to the 5V (straight females). How can I add them? I haven't used KiCAD, but when I try to create the STEP file it's created with no connectors (and I've tried multiple versions)

**Comment by esden** [comment]
@madding1602 This is not the right place to ask the question. It is bad style to jump onto some other github issue that has nothing to do with your project. You should join the KiCad Discord server and ask there instead: https://discord.gg/xvnRc9EY

That said, if you want the part footprints to export together with the board using STEP, you have to make sure that the part models are also STEP and not WRL. If you have further questions please ask them on the KiCad User Discord server.

**Comment by madding1602** [comment]
> @madding1602 This is not the right place to ask the question. It is bad style to jump onto some other github issue that has nothing to do with your project. You should join the KiCad Discord server and ask there instead: https://discord.gg/xvnRc9EY
> 
> That said, if you want the part footprints to export together with the board using STEP, you have to make sure that the part models are also STEP and not WRL. If you have further questions please ask them on the KiCad User Discord server.

okay. thanks!
